version: '3.3'

volumes:
  postgres_volume:

services:
  postgres-mdm:
    image: postgres:latest
    container_name: postgres-mdm
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mdm
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Ab123456
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: unless-stopped